name: allena
description: "TBD"
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.9.0
  get_it: ^8.2.0
  privy_flutter: ^0.3.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true